# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='box_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.FreezerBox'),
        ),
    ]
