# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0002_auto_20160223_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Building Name')),
                ('institution', models.CharField(max_length=128, verbose_name='Building Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Freezer Name')),
                ('temperature', models.SmallIntegerField(verbose_name='Freezer Temperature')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.Building')),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
        migrations.AlterField(
            model_name='freezerbox',
            name='description',
            field=models.TextField(verbose_name='Freezer Box Description'),
        ),
        migrations.AlterField(
            model_name='freezerbox',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Freezer Box Name'),
        ),
        migrations.AddField(
            model_name='freezerbox',
            name='freezer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backbone.Freezer'),
            preserve_default=False,
        ),
    ]
